GET http://localhost:3000


###Login Route
POST http://localhost:3000/Auth/login

###Logout Route
DELETE http://localhost:3000/Auth/logout

###Refresh-Token Route
POST http://localhost:3000/Auth/refresh-token

###Register Route
POST http://localhost:3000/Auth/register
Content-Type: application/json

{
    "email":"amit1213@gmail.com",
    "password":"Amit@123"
}
